# Generated by Django 5.1.1 on 2024-09-28 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_userprofile_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('latest_course', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('years_of_experience', models.IntegerField()),
                ('current_employer', models.BooleanField(default=False)),
                ('availability_to_join', models.CharField(choices=[('immediately', 'Immediately'), ('one_month', 'One Month'), ('three_months', 'Three Months'), ('more_than_a_year', 'More than a Year')], max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], max_length=50)),
                ('marital_status', models.CharField(choices=[('unmarried', 'Unmarried'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced'), ('separated', 'Separated'), ('others', 'Others')], max_length=50)),
                ('differently_abled', models.BooleanField(default=False)),
                ('career_break', models.BooleanField(default=False)),
                ('hometown', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('skills', models.ManyToManyField(related_name='users', to='adminpanel.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('proficient', 'Proficient'), ('expert', 'Expert')], max_length=50)),
                ('read', models.BooleanField(default=False)),
                ('write', models.BooleanField(default=False)),
                ('speak', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='adminpanel.completeprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
