# Generated by Django 5.1.1 on 2024-09-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_completeprofile_languageproficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
