# Generated by Django 5.1.1 on 2024-09-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_completeprofile_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
