# Generated by Django 5.1.1 on 2024-09-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_completeprofile_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSkill',
        ),
    ]
