# Generated by Django 5.1.1 on 2024-09-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_delete_jobskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Data Engineer', max_length=255)),
                ('company_name', models.CharField(default='Aptagrim Consulting', max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_reviews', models.DecimalField(decimal_places=2, default=2.97, max_digits=3)),
                ('experience_required', models.CharField(choices=[('freshers', 'freshers'), ('0 - 2 years', '0 - 2 years'), ('2 - 4 years', '2 - 4 years'), ('4 - 6 years', '4 - 6 years'), ('6 - 8 years', '6 - 8 years'), ('8+ years', '8+ years')], default='0 - 2 years', max_length=50)),
                ('salary', models.CharField(default='Not Disclosed', max_length=100)),
                ('location', models.CharField(default='Hyderabad', max_length=100)),
                ('openings', models.IntegerField(default=1)),
                ('applicants', models.IntegerField(default=2447)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('job_description', models.TextField(default='As a Data Engineer, you will work closely with our development team...')),
                ('preferred_candidate_profile', models.TextField(default='Bachelors or Masters Degree in Computer Science, Engineering, Data Science, or a related field.')),
                ('role', models.CharField(default='Data Engineer', max_length=255)),
                ('industry_type', models.CharField(choices=[('IT Services & Consulting', 'IT Services & Consulting'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Telecommunications', 'Telecommunications')], default='IT Services & Consulting', max_length=255)),
                ('department', models.CharField(default='Data Science & Analytics', max_length=255)),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Temporary', 'Temporary'), ('Freelance', 'Freelance')], default='Full Time', max_length=100)),
                ('role_category', models.CharField(choices=[('Data Science & Machine Learning', 'Data Science & Machine Learning'), ('Software Development', 'Software Development'), ('IT Infrastructure & Support', 'IT Infrastructure & Support'), ('Project Management', 'Project Management'), ('UI/UX Design', 'UI/UX Design'), ('QA & Testing', 'QA & Testing')], default='Data Science & Machine Learning', max_length=255)),
                ('education', models.CharField(choices=[('B.Tech/B.E. in Computers', 'B.Tech/B.E. in Computers'), ('M.Tech/M.E. in Computers', 'M.Tech/M.E. in Computers'), ('Bachelors in Data Science', 'Bachelors in Data Science'), ('Masters in Data Science', 'Masters in Data Science'), ('Bachelors in Engineering', 'Bachelors in Engineering'), ('Masters in Engineering', 'Masters in Engineering'), ('Other', 'Other')], default='B.Tech/B.E. in Computers', max_length=255)),
                ('key_skills', models.TextField(default='Data Science, Java, Scrapy, SQL/NoSQL, Python, etc.')),
            ],
        ),
    ]
