# Generated by Django 5.1.1 on 2024-09-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_remove_jobs_company_reviews_remove_jobs_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='education',
            field=models.TextField(default='UG: Any Graduate  , PG: Any Postgraduate'),
        ),
    ]
