# Generated by Django 5.1.1 on 2024-09-29 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_jobs_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='adminpanel.company'),
            preserve_default=False,
        ),
    ]
