# Generated by Django 5.1.1 on 2024-09-29 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_alter_jobs_company_name_alter_jobs_education_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(choices=[('freshers', 'freshers'), ('0 - 2 years', '0 - 2 years'), ('2 - 4 years', '2 - 4 years'), ('4 - 6 years', '4 - 6 years'), ('6 - 8 years', '6 - 8 years'), ('8+ years', '8+ years')], default='0 - 2 years', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='industry_type',
            field=models.CharField(choices=[('IT Services & Consulting', 'IT Services & Consulting'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Telecommunications', 'Telecommunications')], default='IT Services & Consulting', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='key_skills',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='job',
            name='openings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='adminpanel.company'),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('registration_id', models.CharField(max_length=50, unique=True)),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.companyprofile'),
        ),
    ]
