# Generated by Django 5.1.1 on 2024-09-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_remove_job_salary_range_job_experience_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='completeprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media//'),
        ),
    ]
