# Generated by Django 5.1.1 on 2024-09-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_alter_company_logo_alter_companyprofile_company_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
