# Generated by Django 5.1.1 on 2024-09-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_remove_jobs_company_delete_company_delete_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CT', 'Contract'), ('FR', 'Freelance'), ('IN', 'Internship')], default='FT', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.CharField(choices=[('freshers', 'Freshers'), ('0 - 2 years', '0 - 2 years'), ('2 - 4 years', '2 - 4 years'), ('4 - 6 years', '4 - 6 years'), ('6 - 8 years', '6 - 8 years'), ('8+ years', '8+ years')], default='0 - 2 years', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='openings',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
