# Generated by Django 5.1.1 on 2024-10-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_alter_completeprofile_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languageproficiency',
            old_name='user_profile',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='languageproficiency',
            name='language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='languageproficiency',
            name='proficiency',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Proficient', 'Proficient'), ('Expert', 'Expert')], max_length=50),
        ),
    ]
