# Generated by Django 5.1.1 on 2024-10-01 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_rename_user_profile_languageproficiency_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageproficiency',
            name='proficiency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='languageproficiency',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.completeprofile'),
        ),
    ]
