# Generated by Django 5.1.1 on 2024-10-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_alter_applicationnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
