# Generated by Django 5.1.1 on 2024-10-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_companyprofile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('company', 'New Company Added'), ('job', 'New Job Added'), ('user', 'New User Registered')], max_length=50)),
                ('content_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
